[INFO 19:22:42] my_main *******************
[INFO 19:22:42] my_main WANDB RUN ID:
[INFO 19:22:42] my_main s52hb9dy
[INFO 19:22:42] my_main *******************
shape of state: 73
shape of observation: 73
[INFO 19:22:44] my_main Beginning training for 20000000.0 timesteps
[INFO 19:22:44] my_main t_env: 600 / 20000000.0
[INFO 19:22:44] my_main Estimated time left: 2 minutes, 6 seconds. Time passed: 0 seconds
[INFO 19:22:45] my_main New best model saved with performance: 0.0
/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py:179: UserWarning: tee_stdout.wait timeout. Forcibly terminating.
  warnings.warn("tee_stdout.wait timeout. Forcibly terminating.")
[DEBUG 19:23:11] pymarl Stopping Heartbeat
[WARNING 19:23:11] pymarl Aborted after 0:00:32!
Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 164, in tee_output_fd
    yield out  # let the caller do their printing
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 45, in my_main
    run(_run, config, _log)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 78, in run
    run_sequential(args=args, logger=logger)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 215, in run_sequential
    episode_batch = runner.run(test_mode=False)
  File "/Users/alexwang/phD/ComplexOvercooked/src/runners/episode_runner.py", line 119, in run
    self.batch.update(post_transition_data, ts=self.t)
  File "/Users/alexwang/phD/ComplexOvercooked/src/components/episode_buffer.py", line 116, in update
    v = transform.transform(v)
  File "/Users/alexwang/phD/ComplexOvercooked/src/components/transforms.py", line 16, in transform
    def transform(self, tensor):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 141, in <module>
    ex.run_commandline(params)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 313, in run_commandline
    return self.run(
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 277, in run
    run()
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 234, in __call__
    with capture_stdout() as self._output_file:
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 183, in tee_output_fd
    tee_stderr.wait(timeout=1)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1222, in wait
    self._wait(timeout=sigint_timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 164, in tee_output_fd
    yield out  # let the caller do their printing
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 45, in my_main
    run(_run, config, _log)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 78, in run
    run_sequential(args=args, logger=logger)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 215, in run_sequential
    episode_batch = runner.run(test_mode=False)
  File "/Users/alexwang/phD/ComplexOvercooked/src/runners/episode_runner.py", line 119, in run
    self.batch.update(post_transition_data, ts=self.t)
  File "/Users/alexwang/phD/ComplexOvercooked/src/components/episode_buffer.py", line 116, in update
    v = transform.transform(v)
  File "/Users/alexwang/phD/ComplexOvercooked/src/components/transforms.py", line 16, in transform
    def transform(self, tensor):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 141, in <module>
    ex.run_commandline(params)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 313, in run_commandline
    return self.run(
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 277, in run
    run()
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 234, in __call__
    with capture_stdout() as self._output_file:
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 183, in tee_output_fd
    tee_stderr.wait(timeout=1)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1222, in wait
    self._wait(timeout=sigint_timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt
