[INFO 14:09:46] my_main *******************
[INFO 14:09:46] my_main WANDB RUN ID:
[INFO 14:09:46] my_main qzs05n26
[INFO 14:09:46] my_main *******************
shape of state: 69
shape of observation: 69
[INFO 14:09:48] my_main Beginning training for 20000000.0 timesteps
[INFO 14:09:48] my_main t_env: 600 / 20000000.0
[INFO 14:09:48] my_main Estimated time left: 1 minutes, 27 seconds. Time passed: 0 seconds
[INFO 14:09:49] my_main New best model saved with performance: 0.0
[INFO 14:10:20] my_main t_env: 51000 / 20000000.0
[INFO 14:10:20] my_main Estimated time left: 3 hours, 30 minutes, 41 seconds. Time passed: 32 seconds
[INFO 14:10:58] my_main t_env: 101400 / 20000000.0
[INFO 14:10:58] my_main Estimated time left: 4 hours, 12 minutes, 42 seconds. Time passed: 1 minutes, 10 seconds
[INFO 14:11:36] my_main t_env: 151800 / 20000000.0
[INFO 14:11:36] my_main Estimated time left: 4 hours, 8 minutes, 17 seconds. Time passed: 1 minutes, 48 seconds
[INFO 14:12:14] my_main t_env: 202200 / 20000000.0
[INFO 14:12:14] my_main Estimated time left: 4 hours, 4 minutes, 39 seconds. Time passed: 2 minutes, 25 seconds
[DEBUG 14:12:22] pymarl Stopping Heartbeat
[WARNING 14:12:22] pymarl Aborted after 0:02:39!
Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 164, in tee_output_fd
    yield out  # let the caller do their printing
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 45, in my_main
    run(_run, config, _log)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 72, in run
    run_sequential(args=args, logger=logger)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 223, in run_sequential
    learner.train(episode_sample, runner.t_env, episode)
  File "/Users/alexwang/phD/ComplexOvercooked/src/learners/q_learner.py", line 86, in train
    target_agent_outs = self.target_mac.forward(batch, t=t)
  File "/Users/alexwang/phD/ComplexOvercooked/src/controllers/basic_controller.py", line 27, in forward
    agent_outs, self.hidden_states = self.agent(agent_inputs, self.hidden_states)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/alexwang/phD/ComplexOvercooked/src/modules/agents/rnn_agent.py", line 27, in forward
    h = self.rnn(x, h_in)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 1812, in forward
    ret = _VF.gru_cell(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 141, in <module>
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 313, in run_commandline
    return self.run(
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 277, in run
    run()
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 234, in __call__
    with capture_stdout() as self._output_file:
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 177, in tee_output_fd
    tee_stdout.wait(timeout=1)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1222, in wait
    self._wait(timeout=sigint_timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 164, in tee_output_fd
    yield out  # let the caller do their printing
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 45, in my_main
    run(_run, config, _log)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 72, in run
    run_sequential(args=args, logger=logger)
  File "/Users/alexwang/phD/ComplexOvercooked/src/run.py", line 223, in run_sequential
    learner.train(episode_sample, runner.t_env, episode)
  File "/Users/alexwang/phD/ComplexOvercooked/src/learners/q_learner.py", line 86, in train
    target_agent_outs = self.target_mac.forward(batch, t=t)
  File "/Users/alexwang/phD/ComplexOvercooked/src/controllers/basic_controller.py", line 27, in forward
    agent_outs, self.hidden_states = self.agent(agent_inputs, self.hidden_states)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/alexwang/phD/ComplexOvercooked/src/modules/agents/rnn_agent.py", line 27, in forward
    h = self.rnn(x, h_in)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 1812, in forward
    ret = _VF.gru_cell(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexwang/phD/ComplexOvercooked/src/main_debug.py", line 141, in <module>
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 313, in run_commandline
    return self.run(
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/experiment.py", line 277, in run
    run()
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/run.py", line 234, in __call__
    with capture_stdout() as self._output_file:
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/site-packages/sacred/stdout_capturing.py", line 177, in tee_output_fd
    tee_stdout.wait(timeout=1)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1222, in wait
    self._wait(timeout=sigint_timeout)
  File "/Users/alexwang/miniforge3/envs/llm_rl/lib/python3.10/subprocess.py", line 1953, in _wait
    time.sleep(delay)
KeyboardInterrupt
